<template>
  <RouterView />
</template>

<script setup lang="ts">
import { RouterView } from "vue-router";
import "@/styles/globals.scss";
import config from "@/config";
import "highlight.js/styles/github-dark.css";

// ASCII banner generated by https://manytools.org/hacker-tools/ascii-banner/
// Font "slant"
const banner = `
 _    __         ______                  
| |  / /_  _____/_  __/__  _________ ___ 
| | / / / / / _ \\/ / / _ \\/ ___/ __ \`__ \\
| |/ / /_/ /  __/ / /  __/ /  / / / / / /
|___/\\__,_/\\___/_/  \\___/_/  /_/ /_/ /_/ 
                                          
                                            `;

const consoleMessage = `\
${banner}

Powered by %cVueTerm%c${config.info.version}%c
`;

console.log(
  consoleMessage,
  "background: #22c55e; color: #1c1917; padding: 8px; font-weight: bold",
  "background: #1c1917; color: #22c55e; padding: 8px;",
  ""
);
</script>
